name: Update Spotify Now Playing

on:
  schedule:
    - cron: '*/30 * * * *'  # her 30 dakikada bir
  workflow_dispatch:

jobs:
  spotify-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Update Now Playing Section
        uses: andrediasdev/spotify-readme-action@v1
        with:
          spotify_token: ${{ secrets.SPOTIFY_TOKEN }}
          spotify_user_id: 2thctisnfj2k6fo9ruyvexf2r
          format: '🎶 Now Playing: [{{song}}]({{url}}) by {{artist}}'

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "chore: update Spotify Now Playing"
          git push
